name: My Workflow
on:
  push:
  pull_request:

env:
  MIRROR_URL: git@github.com:Queen229/mirror_nancy_cutie_iconic.git
  EXECUTABLES: mysh

jobs:
 skip_conditions:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.skip }}
    steps:
      - name: Check if branch starts with ga-ignore- or repo is mirror
        id: skip_check
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/ga-ignore-"* ]] || \
             [[ "git@github.com:${{ github.repository }}.git" == "${{ env.MIRROR_URL }}" ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
 check_coding_style:
    needs: skip_conditions
    if: needs.skip_conditions.outputs.should_skip == 'false'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run coding style checker
        run: check.sh $(pwd) $(pwd)

      - name: Annotate coding style errors
        run: |
          if [ -f coding-style-reports.log ]; then
            while IFS= read -r line; do
              FILE=$(echo "$line" | cut -d ':' -f1)
              LINE_NUM=$(echo "$line" | cut -d ':' -f2)
              MSG=$(echo "$line" | cut -d ':' -f3-)
              echo "::error file=$FILE,line=$LINE_NUM::$MSG"
            done < coding-style-reports.log
            exit 1
          fi